build:
  version: "3.0"

accounts:
  message: "Welcome to Goliath National Bank accounts related docker APIs "
  contactDetails:
    name: "Anne Duderstadt - Developer"
    email: "anne@goliath.com"
  onCallSupport:
    - (734) 936-3191
    - (734) 936-3192
